[package]
name = "rust-simple-httpd"
version = "0.1.0"
edition = "2021"

[features]
default = ["color"]
color = []
humantime = ["time/local-offset"]

[dependencies]
anyhow = "1"
indoc = "2"
log = "0"
num_cpus = "1"
signal-hook = "0"
time = { version = "0", features = [ "formatting", "serde-well-known" ] }
tokio = { version = "1", default-features = false, features = ["net", "io-util", "rt", "fs", "time", "sync", "tokio-macros", "macros", "rt-multi-thread"] }

