[package]
name = "rust-simple-httpd"
version = "0.1.0"
edition = "2021"

[features]
default = ["color"]
color = []
humantime = ["time/local-offset"]

[dependencies]
anyhow = "1.0"
indoc = "2.0"
log = "0.4"
num_cpus = "1.15"
signal-hook = "0.3"
time = { version = "0.3", features = [ "formatting", "serde-well-known" ] }
tokio = { version = "1.27", features = ["full"] }

