[package]
name = "rust-simple-httpd"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.15.0"
signal-hook = "0.3.15"
time = { version = "0.3.20", features = [ "formatting", "serde-well-known" ] }
log = "0.4.17"
env_logger = "0.10.0"
indoc = "2.0.1"
