[package]
name = "rust-simple-httpd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
env_logger = "0.10"
indoc = "2.0"
log = "0.4"
num_cpus = "1.15"
signal-hook = "0.3"
time = { version = "0.3", features = [ "formatting", "serde-well-known" ] }
tokio = { version = "1.27", features = ["full"] }
